spring.application.name=DentalSurgeriesAppointments
server.servlet.context-path=/adsweb

# PostgreSQL DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/myadsdentalsurgerydb_lab6
spring.datasource.username=lab5
spring.datasource.password=lab5
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
